language: node_js
node_js:
  - "12"
env:
  global:
  - ZOOKEEPER_PEERS=localhost:2181
  - KAFKA_PEERS=localhost:9092
  - CXX=g++-4.8

script:
  - rm -rf node_modules
  - yarn
  - yarn add --frozen-lockfile node-rdkafka@2.7.4
  - yarn lint
  - mocha --exit --timeout 60000 -R spec test/int/*

before_install:
- wget https://archive.apache.org/dist/kafka/1.1.0/kafka_2.11-1.1.0.tgz -O kafka.tgz
- mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
- nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
- nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"
- sleep 12
- kafka/bin/kafka-topics.sh --create --partitions 1 --replication-factor 1 --topic my-input-topic --zookeeper localhost:2181
- kafka/bin/kafka-topics.sh --create --partitions 1 --replication-factor 1 --topic my-output-topic --zookeeper localhost:2181
- sleep 2

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
